# Generated by Django 5.0 on 2024-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='types',
            field=models.CharField(default='flowers', max_length=100),
        ),
    ]
