# Generated by Django 5.1.1 on 2024-09-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_id", models.IntegerField()),
                ("full_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("phone", models.IntegerField(max_length=10)),
            ],
        ),
    ]
