# Generated by Django 5.1.1 on 2024-09-25 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_order_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cart_id",
            new_name="product_id",
        ),
        migrations.AddField(
            model_name="order",
            name="estimate_delivery",
            field=models.DateTimeField(default=datetime.date(2024, 9, 28)),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(default=datetime.date(2024, 9, 26)),
        ),
    ]
