# Generated by Django 5.1.1 on 2024-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_cart_id_order_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_id",
            field=models.CharField(max_length=25),
        ),
    ]
