# Generated by Django 5.1.1 on 2024-09-25 20:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_order_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="addtocart",
            name="gift_wrap_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="addtocart",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimate_delivery",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 27, 20, 18, 51, 588685, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
