# Generated by Django 5.1.1 on 2024-09-28 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_addtocart_gift_wrap_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="estimate_delivery",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 30, 5, 38, 10, 759584, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
