# Generated by Django 5.0.3 on 2024-09-29 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_estimate_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimate_delivery',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 3, 23, 20, 34542, tzinfo=datetime.timezone.utc)),
        ),
    ]
