# Generated by Django 5.1.1 on 2024-09-29 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_order_estimate_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="estimate_delivery",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 1, 5, 10, 42, 618882, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
