# Generated by Django 5.1.1 on 2024-09-30 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_order_estimate_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("instagramUsername", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=10)),
                ("followersCount", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="estimate_delivery",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 2, 16, 56, 16, 895985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
