# Generated by Django 5.1.1 on 2024-09-30 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_influenceruser_alter_order_estimate_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="influenceruser",
            name="isInfluencer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="influenceruser",
            name="picture",
            field=models.ImageField(default="", upload_to="influencer_pictures/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimate_delivery",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 2, 17, 11, 53, 920615, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
